version: '3.8'

services:
  ladyclinic_client:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ladyclinic_client
    networks:
      - ladyclinicclient_network
    ports:
      - "15551:3000"
    restart: always

networks:
    ladyclinicclient_network:
      driver: bridge